#!/bin/bash

#Run this script on the Raspberry Pi Zero W, that is supposed to run Chase.
#This will configure the UART to be able to talk to the PSoC
#Be aware that this might affect Bluetooth functionality.

CONFIG=/boot/config.txt
CMDLINE=/boot/cmdline.txt

set -o errexit

printf "\nConfiguring UART on Raspberry Pi to work with Chase"


printf "\nBacking up files '/boot/config.txt' and '/boot/cmdline.txt'"

if ! [ -f "$CONFIG.backup" ]; then
  cp -i $CONFIG $CONFIG.backup
else
  printf "\n ... $CONFIG.backup already exists. Did not overwrite."
fi

if ! [ -f "$CMDLINE.backup" ]; then
  cp -i $CMDLINE $CMDLINE.backup
else
  printf "\n ... $CMDLINE.backup already exists. Did not overwrite."
fi

printf "\n ... done!"


printf "\n\nAdding overlay 'miniuart-bt' to /boot/config.txt"
if ! grep -Fxq "dtoverlay=miniuart-bt" /boot/config.txt; then
  printf "\n## Use ttyAMA0 for UART instead of Bluetooth\ndtoverlay=miniuart-bt" >> /boot/config.txt
  printf "\n ... done!"
else 
  printf "\n ... Overlay already present - Nothing changed." 
fi


printf "\n\nRemoving 'console=serial0,115200' from /boot/cmdline.txt"
if grep -Fwq "console=serial0,115200" /boot/cmdline.txt; then
  sed -i 's/console=serial0,115200//g' /boot/cmdline.txt
  printf "\n ... done!"
else
  printf "\n ... 'console=serial0,115200' not found - Nothing changed."
fi


printf "\n\nDisabling login via UART console.\n"
systemctl disable serial-getty@ttyS0.service
printf "\n ... done!"

printf "\nConfiguration finished. Please reboot Raspberry Pi.\n\n"

